(function(){var d=document,w=window,loc=location;var host=loc.hostname.toLowerCase();
var cookies=(d.cookie||'').split(';').map(function(c){return c.trim()}).filter(Boolean).map(function(c){return c.split('=')[0]});
function keys(s){try{return Object.keys(s||{})}catch(e){return[]}}var local=keys(w.localStorage),session=keys(w.sessionStorage);
var srcs=[];[['script[src]','src'],['iframe[src]','src'],['img[src]','src'],['link[href]','href']].forEach(function(p){[].slice.call(d.querySelectorAll(p[0])).forEach(function(e){srcs.push(e.getAttribute(p[1]))})});
var hosts={};srcs.forEach(function(u){var h='';try{h=new URL(u,loc.href).hostname.toLowerCase()}catch(e){return}if(h)hosts[h]=(hosts[h]||0)+1});function rel(h){return h===host?'même hôte':(h.slice(-(host.length+1))==='.'+host?'sous-domaine de la page':'hôte distinct — appartenance non déterminée')}var all=Object.keys(hosts).map(function(h){return{hostname:h,count:hosts[h],relation:rel(h)}}).sort(function(a,b){return b.count-a.count});var tp=all.filter(function(x){return x.relation.indexOf('distinct')===0});
var old=d.getElementById('consent-inv');if(old)old.remove();var p=d.createElement('div');p.id='consent-inv';p.setAttribute('role','dialog');p.setAttribute('aria-label','Inventaire consentement');p.style.cssText='position:fixed;top:12px;right:12px;z-index:2147483647;max-width:440px;max-height:80vh;overflow:auto;background:#fff;color:#111;border:2px solid #0b6e4f;border-radius:8px;padding:12px;font:14px/1.4 system-ui,sans-serif;box-shadow:0 4px 16px rgba(0,0,0,.25)';
function li(a){return a.length?'<ul style="padding-left:18px">'+a.map(function(x){return'<li>'+String(x).replace(/</g,'&lt;')+'</li>'}).join('')+'</ul>':'<em>aucun</em>'}
p.innerHTML='<strong>Inventaire consentement</strong> — '+host+'<br><small>Pour mesurer l\'état <b>avant consentement</b> : ouvrez la page en navigation privée sans cliquer sur la bannière, puis lancez l\'inventaire.</small><h4>Cookies ('+cookies.length+')</h4>'+li(cookies)+'<h4>localStorage ('+local.length+')</h4>'+li(local)+'<h4>sessionStorage ('+session.length+')</h4>'+li(session)+'<h4>Hôtes distincts ('+tp.length+')</h4>'+li(tp.map(function(t){return t.hostname+' ×'+t.count}))+'<h4>Tous les hôtes ('+all.length+')</h4>'+li(all.map(function(t){return t.hostname+' ×'+t.count+' — '+t.relation}))+'<p><small>Règle conservatrice : même hôte / sous-domaine de la page / hôte distinct. L\'appartenance juridique d\'un hôte distinct n\'est pas déterminée par l\'outil.</small></p>'+'<p><small>Les cookies HttpOnly ne sont pas visibles par script. Outil d\'inventaire, pas un avis juridique.</small></p><button id="cinv-copy">Copier le JSON</button> <button id="cinv-close">Fermer</button>';d.body.appendChild(p);
d.getElementById('cinv-close').onclick=function(){p.remove()};d.getElementById('cinv-copy').onclick=function(){var t=JSON.stringify({url:loc.href,date:new Date().toISOString(),cookies:cookies,localStorage:local,sessionStorage:session,hosts:all,thirdParties:tp,rule:'same host / subdomain / other host (ownership undetermined)'},null,2);if(navigator.clipboard)navigator.clipboard.writeText(t);else prompt('JSON',t)};})();
